name: 04 â€“ Workflow uses Actions
on: 
  #push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: ./CWICZENIA/04-praca-z-zewnetrzymi-akcjami/react-app
    steps:
      - name: Checkout Code
        uses:  actions/checkout@v3 
      - name: Printing Folders
        run: ls -la         
      - name: Setup node          
        uses:  actions/setup-node@v4
        with:
          node-version: 18
      - name: Check version nodejs
        run: |
          npm -v
          node -v    
      - name: Run test
        run: npm run test    