name: 07 â€“ Using Expressions

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Is debug?"
        type: boolean
        default: true
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest    
    steps:
      - name: Print start-up data
        if: ${{inputs.debug == true}}
        run: |
          echo Triggered by: ${{github.action}}
          echo Branch: ${{github.ref}}
          echo Commit ${{github.sha}}
          echo Runner OS: ${{runner.os}}
      - name: Print when triggered from main
        if: ${{ (inputs.debug == true) && (github.ref_name == 'main')}}
        run: echo "I was triggered from main"
      - name: Greeting
        run: |
          echo "Hello, world"
          echo ${{inputs.debug}}

