name: 09 â€“ Using Functions

on:
  workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: Failing step
        run: exit 1  
      - name: I will be skipped
        if: ${{success()}}
        run: echo I will print if previous steps succeed.  
      - name: I will execute
        if: ${{failure()}}
        run: echo I will print if any previous step fails.  
      - name: I will execute
        if: ${{!cancalled()}}  
        run: echo I will always print, except when the workflow is cancelled
      - name: I will execute when cancelled
        if: ${{cancelled()}}
        run: echo I was cancalled  