name: 12 – Working with Outputs
on:
  workflow_dispatch:
    inputs:   
      build-status:
        description: "Is success?"
        type: choice
        options:
          - success
          - failure
        default: success
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build  
        id: build
        run: status=${{inputs.build-status}} >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{inputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo Wdrażanie
